//! Contract generation module with AI-generated legal documents
//!
//! All contract bodies, summaries, and clauses are generated by the LLM router.
//! Nothing hardcoded. Templates define only the prompts (user input fields).

use crate::llm_router::{GenerationRequest, LLMProfile, LLMRouter};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;

/// AI system prompt instructing the LLM how to generate legal documents.
const CONTRACT_SYSTEM_PROMPT: &str = r#"You are the Legal Document Generator inside Digital Product Factory, an AI-powered desktop application for creating professional contracts and agreements.

## Your Role
You generate properly formatted legal documents based on user input. You receive a contract type, the user's specific answers to prompts, and must return legally-structured text.

## Output Format
Return ONLY valid JSON. No markdown, no code fences. The JSON structure must be:
{
  "title": "string",
  "content": "string",
  "plain_english_summary": "string",
  "additional_notes": "string"
}

## Formatting Rules for content field
- Use proper legal formatting with numbered clauses (1., 2., 3., etc.)
- Section headings should be in ALL CAPS or Title Case
- Each clause should cover a distinct legal topic
- Include placeholders for signatures and dates at the bottom
- For the title: use a professional agreement title matching the contract type

## Content Rules
- Include standard clauses: Parties, Services/Agreement, Term, Payment/Compensation (when applicable), Confidentiality (when applicable), Intellectual Property (when applicable), Limitation of Liability, Termination, Governing Law, Entire Agreement, Signatures
- Adapt the clauses to match the specific contract type and user answers
- Use clear, enforceable legal language
- Keep placeholders for dates and signatures using "_____" lines

## Summary (plain_english_summary)
Write 2-3 plain-English sentences explaining what this contract does. No legal jargon. Focus on the key rights and obligations of each party.

## Notes (additional_notes)
Optional: 1-2 sentences about what the user should know about this type of agreement - common pitfalls, when to get a lawyer, etc.

## Important
- This is a template generator, not legal advice
- Include a brief disclaimer note in the content footer
- Do NOT fabricate state-specific legal citations
- Use gender-neutral language
- Maximum content length: 3000 words"#;

#[derive(Debug, Clone)]
pub struct ContractGenerator {
    templates: HashMap<String, ContractTemplate>,
    llm_router: Option<LLMRouter>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ContractTemplate {
    pub id: String,
    pub name: String,
    pub description: String,
    pub category: ContractCategory,
    pub prompts: Vec<ContractPrompt>,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[allow(clippy::upper_case_acronyms)]
pub enum ContractCategory {
    Freelance,
    NDA,
    Employment,
    Rental,
    Sales,
    Partnership,
    Consulting,
    Coaching,
    Custom,
}

impl ContractCategory {
    pub fn name(&self) -> &'static str {
        match self {
            ContractCategory::Freelance => "Freelance",
            ContractCategory::NDA => "NDA",
            ContractCategory::Employment => "Employment",
            ContractCategory::Rental => "Rental",
            ContractCategory::Sales => "Sales",
            ContractCategory::Partnership => "Partnership",
            ContractCategory::Consulting => "Consulting",
            ContractCategory::Coaching => "Coaching",
            ContractCategory::Custom => "Custom",
        }
    }

    pub fn all() -> Vec<ContractCategory> {
        vec![
            ContractCategory::Freelance,
            ContractCategory::NDA,
            ContractCategory::Employment,
            ContractCategory::Rental,
            ContractCategory::Sales,
            ContractCategory::Partnership,
            ContractCategory::Consulting,
            ContractCategory::Coaching,
        ]
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ContractPrompt {
    pub field: String,
    pub question: String,
    pub placeholder: String,
    pub required: bool,
    pub help_text: String,
    pub field_type: FieldType,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum FieldType {
    Text,
    Number,
    Date,
    Select(Vec<String>),
    TextArea,
    Currency,
    Email,
}

#[derive(Debug, Clone)]
pub struct GeneratedContract {
    pub title: String,
    pub content: String,
    pub plain_english_summary: String,
    pub disclaimer: String,
}

/// JSON structure returned by the LLM for contract generation.
#[derive(Debug, Clone, Serialize, Deserialize)]
struct LlmContractResponse {
    title: String,
    content: String,
    plain_english_summary: String,
    #[serde(default)]
    additional_notes: String,
}

impl ContractGenerator {
    pub fn new() -> Self {
        let mut generator = Self {
            templates: HashMap::new(),
            llm_router: None,
        };
        generator.load_templates();
        generator
    }

    pub fn set_api_keys(
        &mut self,
        openai: String,
        anthropic: String,
        google: String,
        deepseek: String,
        moonshot: String,
    ) {
        self.llm_router = Some(LLMRouter::new(
            openai, anthropic, google, deepseek, moonshot,
        ));
    }

    fn load_templates(&mut self) {
        // All 9 categories get at least 1 template.
        // Templates define ONLY prompts (user input fields).
        // Contract bodies are generated by the LLM router.
        let templates = vec![
            // -- Freelance ------------------------------------------
            ContractTemplate {
                id: "freelance_service".to_string(),
                name: "Freelance Service Agreement".to_string(),
                description: "Standard agreement for freelance services".to_string(),
                category: ContractCategory::Freelance,
                prompts: vec![
                    ContractPrompt {
                        field: "client_name".to_string(),
                        question: "What is the client's full name or company name?".to_string(),
                        placeholder: "e.g., Acme Corporation".to_string(),
                        required: true,
                        help_text: "Full legal name as it will appear on the contract".to_string(),
                        field_type: FieldType::Text,
                    },
                    ContractPrompt {
                        field: "freelancer_name".to_string(),
                        question: "What is your full name or business name?".to_string(),
                        placeholder: "e.g., Jane Smith".to_string(),
                        required: true,
                        help_text: "Your full legal name".to_string(),
                        field_type: FieldType::Text,
                    },
                    ContractPrompt {
                        field: "service_description".to_string(),
                        question: "Describe the services you will provide:".to_string(),
                        placeholder: "e.g., Website design and development...".to_string(),
                        required: true,
                        help_text: "Be specific about deliverables".to_string(),
                        field_type: FieldType::TextArea,
                    },
                    ContractPrompt {
                        field: "payment_amount".to_string(),
                        question: "What is the total payment amount?".to_string(),
                        placeholder: "e.g., 5000".to_string(),
                        required: true,
                        help_text: "Total contract value in dollars".to_string(),
                        field_type: FieldType::Currency,
                    },
                    ContractPrompt {
                        field: "payment_schedule".to_string(),
                        question: "What is the payment schedule?".to_string(),
                        placeholder: "Select schedule".to_string(),
                        required: true,
                        help_text: "When payments are due".to_string(),
                        field_type: FieldType::Select(vec![
                            "50% upfront, 50% on completion".to_string(),
                            "100% upfront".to_string(),
                            "100% on completion".to_string(),
                            "Monthly installments".to_string(),
                        ]),
                    },
                    ContractPrompt {
                        field: "timeline".to_string(),
                        question: "What is the project timeline?".to_string(),
                        placeholder: "e.g., 30 days from contract signing".to_string(),
                        required: true,
                        help_text: "Start date, end date, or duration".to_string(),
                        field_type: FieldType::Text,
                    },
                    ContractPrompt {
                        field: "revisions".to_string(),
                        question: "How many revisions are included?".to_string(),
                        placeholder: "Select number".to_string(),
                        required: true,
                        help_text: "Number of revision rounds before additional fees".to_string(),
                        field_type: FieldType::Select(vec![
                            "1".to_string(),
                            "2".to_string(),
                            "3".to_string(),
                            "Unlimited".to_string(),
                        ]),
                    },
                    ContractPrompt {
                        field: "jurisdiction".to_string(),
                        question: "What state/country governs this contract?".to_string(),
                        placeholder: "e.g., California, USA".to_string(),
                        required: true,
                        help_text: "This determines which laws apply".to_string(),
                        field_type: FieldType::Text,
                    },
                ],
            },
            // -- NDA ------------------------------------------------
            ContractTemplate {
                id: "nda_mutual".to_string(),
                name: "Mutual Non-Disclosure Agreement".to_string(),
                description: "Protect confidential information shared between parties".to_string(),
                category: ContractCategory::NDA,
                prompts: vec![
                    ContractPrompt {
                        field: "party_a".to_string(),
                        question: "First party name:".to_string(),
                        placeholder: "e.g., Company A".to_string(),
                        required: true,
                        help_text: "Full legal name".to_string(),
                        field_type: FieldType::Text,
                    },
                    ContractPrompt {
                        field: "party_b".to_string(),
                        question: "Second party name:".to_string(),
                        placeholder: "e.g., Company B".to_string(),
                        required: true,
                        help_text: "Full legal name".to_string(),
                        field_type: FieldType::Text,
                    },
                    ContractPrompt {
                        field: "purpose".to_string(),
                        question: "What is the purpose of sharing confidential information?".to_string(),
                        placeholder: "e.g., Exploring a potential business partnership...".to_string(),
                        required: true,
                        help_text: "Why information is being shared".to_string(),
                        field_type: FieldType::TextArea,
                    },
                    ContractPrompt {
                        field: "duration_years".to_string(),
                        question: "How many years should the NDA last?".to_string(),
                        placeholder: "e.g., 3".to_string(),
                        required: true,
                        help_text: "Standard is 2-5 years".to_string(),
                        field_type: FieldType::Number,
                    },
                    ContractPrompt {
                        field: "jurisdiction".to_string(),
                        question: "Governing law jurisdiction:".to_string(),
                        placeholder: "e.g., California, USA".to_string(),
                        required: true,
                        help_text: "Which laws apply".to_string(),
                        field_type: FieldType::Text,
                    },
                ],
            },
            ContractTemplate {
                id: "nda_one_way".to_string(),
                name: "One-Way Non-Disclosure Agreement".to_string(),
                description: "Confidentiality agreement where only one party discloses".to_string(),
                category: ContractCategory::NDA,
                prompts: vec![
                    ContractPrompt {
                        field: "disclosing_party".to_string(),
                        question: "Disclosing party name (the one sharing secrets):".to_string(),
                        placeholder: "e.g., InnovateTech Inc.".to_string(),
                        required: true,
                        help_text: "The party sharing confidential information".to_string(),
                        field_type: FieldType::Text,
                    },
                    ContractPrompt {
                        field: "receiving_party".to_string(),
                        question: "Receiving party name (the one keeping secrets):".to_string(),
                        placeholder: "e.g., Venture Partners LLC".to_string(),
                        required: true,
                        help_text: "The party receiving confidential information".to_string(),
                        field_type: FieldType::Text,
                    },
                    ContractPrompt {
                        field: "purpose".to_string(),
                        question: "Purpose of disclosure:".to_string(),
                        placeholder: "e.g., Evaluating a potential investment".to_string(),
                        required: true,
                        help_text: "Why confidential info is being shared".to_string(),
                        field_type: FieldType::TextArea,
                    },
                    ContractPrompt {
                        field: "duration_years".to_string(),
                        question: "How many years should the NDA last?".to_string(),
                        placeholder: "e.g., 3".to_string(),
                        required: true,
                        help_text: "Standard is 2-5 years".to_string(),
                        field_type: FieldType::Number,
                    },
                ],
            },
            // -- Employment -----------------------------------------
            ContractTemplate {
                id: "employment_agreement".to_string(),
                name: "Employment Agreement".to_string(),
                description: "Standard employment contract for full-time or part-time employees".to_string(),
                category: ContractCategory::Employment,
                prompts: vec![
                    ContractPrompt {
                        field: "employer_name".to_string(),
                        question: "Employer company name:".to_string(),
                        placeholder: "e.g., TechCorp Inc.".to_string(),
                        required: true,
                        help_text: "Full legal business name".to_string(),
                        field_type: FieldType::Text,
                    },
                    ContractPrompt {
                        field: "employee_name".to_string(),
                        question: "Employee full name:".to_string(),
                        placeholder: "e.g., John Doe".to_string(),
                        required: true,
                        help_text: "Full legal name of employee".to_string(),
                        field_type: FieldType::Text,
                    },
                    ContractPrompt {
                        field: "job_title".to_string(),
                        question: "Job title:".to_string(),
                        placeholder: "e.g., Senior Software Engineer".to_string(),
                        required: true,
                        help_text: "Official position title".to_string(),
                        field_type: FieldType::Text,
                    },
                    ContractPrompt {
                        field: "salary".to_string(),
                        question: "Annual salary:".to_string(),
                        placeholder: "e.g., 80000".to_string(),
                        required: true,
                        help_text: "Gross annual salary in dollars".to_string(),
                        field_type: FieldType::Currency,
                    },
                    ContractPrompt {
                        field: "start_date".to_string(),
                        question: "Start date:".to_string(),
                        placeholder: "e.g., 2026-08-01".to_string(),
                        required: true,
                        help_text: "First day of employment".to_string(),
                        field_type: FieldType::Date,
                    },
                    ContractPrompt {
                        field: "employment_type".to_string(),
                        question: "Employment type:".to_string(),
                        placeholder: "Select type".to_string(),
                        required: true,
                        help_text: "Full-time, part-time, or contract".to_string(),
                        field_type: FieldType::Select(vec![
                            "Full-time".to_string(),
                            "Part-time".to_string(),
                            "Contract".to_string(),
                        ]),
                    },
                    ContractPrompt {
                        field: "benefits_summary".to_string(),
                        question: "Briefly describe benefits offered:".to_string(),
                        placeholder: "e.g., Health insurance, 15 PTO days, 401k matching".to_string(),
                        required: false,
                        help_text: "Key benefits the employee will receive".to_string(),
                        field_type: FieldType::TextArea,
                    },
                ],
            },
            // -- Rental ---------------------------------------------
            ContractTemplate {
                id: "rental_agreement".to_string(),
                name: "Rental/Lease Agreement".to_string(),
                description: "Residential or commercial property lease".to_string(),
                category: ContractCategory::Rental,
                prompts: vec![
                    ContractPrompt {
                        field: "landlord_name".to_string(),
                        question: "Landlord name:".to_string(),
                        placeholder: "e.g., John Smith".to_string(),
                        required: true,
                        help_text: "Full legal name".to_string(),
                        field_type: FieldType::Text,
                    },
                    ContractPrompt {
                        field: "tenant_name".to_string(),
                        question: "Tenant name:".to_string(),
                        placeholder: "e.g., Jane Doe".to_string(),
                        required: true,
                        help_text: "Full legal name".to_string(),
                        field_type: FieldType::Text,
                    },
                    ContractPrompt {
                        field: "property_address".to_string(),
                        question: "Property address:".to_string(),
                        placeholder: "Full street address".to_string(),
                        required: true,
                        help_text: "Complete address".to_string(),
                        field_type: FieldType::TextArea,
                    },
                    ContractPrompt {
                        field: "monthly_rent".to_string(),
                        question: "Monthly rent amount:".to_string(),
                        placeholder: "e.g., 1500".to_string(),
                        required: true,
                        help_text: "Base monthly rent".to_string(),
                        field_type: FieldType::Currency,
                    },
                    ContractPrompt {
                        field: "security_deposit".to_string(),
                        question: "Security deposit:".to_string(),
                        placeholder: "e.g., 1500".to_string(),
                        required: true,
                        help_text: "Typically 1-2 months rent".to_string(),
                        field_type: FieldType::Currency,
                    },
                    ContractPrompt {
                        field: "lease_term".to_string(),
                        question: "Lease term:".to_string(),
                        placeholder: "Select term".to_string(),
                        required: true,
                        help_text: "Duration of lease".to_string(),
                        field_type: FieldType::Select(vec![
                            "Month-to-month".to_string(),
                            "6 months".to_string(),
                            "1 year".to_string(),
                            "2 years".to_string(),
                        ]),
                    },
                ],
            },
            // -- Sales ----------------------------------------------
            ContractTemplate {
                id: "sales_agreement".to_string(),
                name: "Sales Agreement / Invoice Terms".to_string(),
                description: "Standard terms for sale of goods or services".to_string(),
                category: ContractCategory::Sales,
                prompts: vec![
                    ContractPrompt {
                        field: "seller_name".to_string(),
                        question: "Seller name:".to_string(),
                        placeholder: "e.g., ACME Supplies".to_string(),
                        required: true,
                        help_text: "Selling party legal name".to_string(),
                        field_type: FieldType::Text,
                    },
                    ContractPrompt {
                        field: "buyer_name".to_string(),
                        question: "Buyer name:".to_string(),
                        placeholder: "e.g., Widget Corp".to_string(),
                        required: true,
                        help_text: "Buying party legal name".to_string(),
                        field_type: FieldType::Text,
                    },
                    ContractPrompt {
                        field: "product_description".to_string(),
                        question: "Describe the products or services being sold:".to_string(),
                        placeholder: "e.g., 500 units of custom-printed t-shirts...".to_string(),
                        required: true,
                        help_text: "Detailed description of deliverables".to_string(),
                        field_type: FieldType::TextArea,
                    },
                    ContractPrompt {
                        field: "total_price".to_string(),
                        question: "Total purchase price:".to_string(),
                        placeholder: "e.g., 15000".to_string(),
                        required: true,
                        help_text: "Total amount in dollars".to_string(),
                        field_type: FieldType::Currency,
                    },
                    ContractPrompt {
                        field: "payment_terms".to_string(),
                        question: "Payment terms:".to_string(),
                        placeholder: "Select terms".to_string(),
                        required: true,
                        help_text: "When and how payment is due".to_string(),
                        field_type: FieldType::Select(vec![
                            "Due upon receipt".to_string(),
                            "Net 30".to_string(),
                            "Net 60".to_string(),
                            "50% deposit, 50% on delivery".to_string(),
                        ]),
                    },
                    ContractPrompt {
                        field: "delivery_date".to_string(),
                        question: "Expected delivery date:".to_string(),
                        placeholder: "e.g., 2026-09-15".to_string(),
                        required: true,
                        help_text: "When goods/services will be delivered".to_string(),
                        field_type: FieldType::Date,
                    },
                ],
            },
            // -- Partnership ----------------------------------------
            ContractTemplate {
                id: "partnership_agreement".to_string(),
                name: "Partnership Agreement".to_string(),
                description: "Formal agreement between business partners".to_string(),
                category: ContractCategory::Partnership,
                prompts: vec![
                    ContractPrompt {
                        field: "partner_a_name".to_string(),
                        question: "First partner name:".to_string(),
                        placeholder: "e.g., Alice Johnson".to_string(),
                        required: true,
                        help_text: "Full legal name".to_string(),
                        field_type: FieldType::Text,
                    },
                    ContractPrompt {
                        field: "partner_b_name".to_string(),
                        question: "Second partner name:".to_string(),
                        placeholder: "e.g., Bob Williams".to_string(),
                        required: true,
                        help_text: "Full legal name".to_string(),
                        field_type: FieldType::Text,
                    },
                    ContractPrompt {
                        field: "business_name".to_string(),
                        question: "Partnership business name:".to_string(),
                        placeholder: "e.g., Johnson & Williams Consulting".to_string(),
                        required: true,
                        help_text: "Name under which the partnership operates".to_string(),
                        field_type: FieldType::Text,
                    },
                    ContractPrompt {
                        field: "profit_split".to_string(),
                        question: "Profit/loss split (percentage each):".to_string(),
                        placeholder: "e.g., 50/50".to_string(),
                        required: true,
                        help_text: "How profits and losses are distributed".to_string(),
                        field_type: FieldType::Text,
                    },
                    ContractPrompt {
                        field: "capital_contribution".to_string(),
                        question: "Describe initial capital contributions:".to_string(),
                        placeholder: "e.g., Alice contributes $20,000, Bob contributes $10,000".to_string(),
                        required: true,
                        help_text: "What each partner brings to the partnership".to_string(),
                        field_type: FieldType::TextArea,
                    },
                    ContractPrompt {
                        field: "governance".to_string(),
                        question: "How will major decisions be made?".to_string(),
                        placeholder: "e.g., unanimous consent for major decisions".to_string(),
                        required: true,
                        help_text: "Decision-making structure".to_string(),
                        field_type: FieldType::Text,
                    },
                ],
            },
            // -- Consulting -----------------------------------------
            ContractTemplate {
                id: "consulting_agreement".to_string(),
                name: "Consulting Services Agreement".to_string(),
                description: "Agreement for professional consulting services".to_string(),
                category: ContractCategory::Consulting,
                prompts: vec![
                    ContractPrompt {
                        field: "consultant_name".to_string(),
                        question: "Consultant name:".to_string(),
                        placeholder: "e.g., Sarah Adams Consulting".to_string(),
                        required: true,
                        help_text: "Full legal name or business name".to_string(),
                        field_type: FieldType::Text,
                    },
                    ContractPrompt {
                        field: "client_name".to_string(),
                        question: "Client name:".to_string(),
                        placeholder: "e.g., Global Enterprises Inc.".to_string(),
                        required: true,
                        help_text: "Full legal name".to_string(),
                        field_type: FieldType::Text,
                    },
                    ContractPrompt {
                        field: "scope_of_work".to_string(),
                        question: "Detailed scope of consulting work:".to_string(),
                        placeholder: "e.g., Market analysis, strategy recommendations...".to_string(),
                        required: true,
                        help_text: "Specific services to be provided".to_string(),
                        field_type: FieldType::TextArea,
                    },
                    ContractPrompt {
                        field: "hourly_rate".to_string(),
                        question: "Hourly or flat rate:".to_string(),
                        placeholder: "e.g., $200/hour or $5000 flat".to_string(),
                        required: true,
                        help_text: "Rate structure".to_string(),
                        field_type: FieldType::Text,
                    },
                    ContractPrompt {
                        field: "estimated_hours".to_string(),
                        question: "Estimated total hours or duration:".to_string(),
                        placeholder: "e.g., 40 hours over 2 months".to_string(),
                        required: true,
                        help_text: "Expected time commitment".to_string(),
                        field_type: FieldType::Text,
                    },
                    ContractPrompt {
                        field: "expenses".to_string(),
                        question: "How are expenses handled?".to_string(),
                        placeholder: "Select option".to_string(),
                        required: true,
                        help_text: "Travel and other expenses".to_string(),
                        field_type: FieldType::Select(vec![
                            "Reimbursed at cost".to_string(),
                            "Included in flat rate".to_string(),
                            "Not applicable".to_string(),
                        ]),
                    },
                ],
            },
            // -- Coaching -------------------------------------------
            ContractTemplate {
                id: "coaching_contract".to_string(),
                name: "Coaching Services Contract".to_string(),
                description: "Agreement between coach and client for coaching services".to_string(),
                category: ContractCategory::Coaching,
                prompts: vec![
                    ContractPrompt {
                        field: "coach_name".to_string(),
                        question: "Coach name:".to_string(),
                        placeholder: "e.g., Mike Thompson Coaching".to_string(),
                        required: true,
                        help_text: "Coach's full name or business".to_string(),
                        field_type: FieldType::Text,
                    },
                    ContractPrompt {
                        field: "client_name".to_string(),
                        question: "Client name:".to_string(),
                        placeholder: "e.g., Emily Davis".to_string(),
                        required: true,
                        help_text: "Client's full name".to_string(),
                        field_type: FieldType::Text,
                    },
                    ContractPrompt {
                        field: "coaching_type".to_string(),
                        question: "Type of coaching:".to_string(),
                        placeholder: "e.g., Life coaching, Business coaching".to_string(),
                        required: true,
                        help_text: "The focus area".to_string(),
                        field_type: FieldType::Text,
                    },
                    ContractPrompt {
                        field: "session_count".to_string(),
                        question: "Number of sessions included:".to_string(),
                        placeholder: "e.g., 12".to_string(),
                        required: true,
                        help_text: "Total sessions in the package".to_string(),
                        field_type: FieldType::Number,
                    },
                    ContractPrompt {
                        field: "session_length".to_string(),
                        question: "Session length (minutes):".to_string(),
                        placeholder: "e.g., 60".to_string(),
                        required: true,
                        help_text: "Duration of each session".to_string(),
                        field_type: FieldType::Number,
                    },
                    ContractPrompt {
                        field: "total_fee".to_string(),
                        question: "Total fee for the coaching package:".to_string(),
                        placeholder: "e.g., 2400".to_string(),
                        required: true,
                        help_text: "Full package price in dollars".to_string(),
                        field_type: FieldType::Currency,
                    },
                    ContractPrompt {
                        field: "payment_plan".to_string(),
                        question: "Payment plan:".to_string(),
                        placeholder: "Select option".to_string(),
                        required: true,
                        help_text: "How payments are made".to_string(),
                        field_type: FieldType::Select(vec![
                            "Paid in full upfront".to_string(),
                            "Monthly installments".to_string(),
                            "Pay per session".to_string(),
                        ]),
                    },
                ],
            },
            // -- Custom ---------------------------------------------
            ContractTemplate {
                id: "custom_contract".to_string(),
                name: "Custom Agreement".to_string(),
                description: "Create a custom agreement with your own description and terms".to_string(),
                category: ContractCategory::Custom,
                prompts: vec![
                    ContractPrompt {
                        field: "party_a".to_string(),
                        question: "First party name:".to_string(),
                        placeholder: "e.g., Party A or Company Name".to_string(),
                        required: true,
                        help_text: "Full legal name".to_string(),
                        field_type: FieldType::Text,
                    },
                    ContractPrompt {
                        field: "party_b".to_string(),
                        question: "Second party name:".to_string(),
                        placeholder: "e.g., Party B or Company Name".to_string(),
                        required: true,
                        help_text: "Full legal name".to_string(),
                        field_type: FieldType::Text,
                    },
                    ContractPrompt {
                        field: "agreement_type".to_string(),
                        question: "What type of agreement is this?".to_string(),
                        placeholder: "e.g., Service agreement, Licensing deal...".to_string(),
                        required: true,
                        help_text: "Briefly describe the nature of this agreement".to_string(),
                        field_type: FieldType::Text,
                    },
                    ContractPrompt {
                        field: "key_terms".to_string(),
                        question: "Describe the key terms and obligations:".to_string(),
                        placeholder: "e.g., Party A will provide X service, Party B will pay Y...".to_string(),
                        required: true,
                        help_text: "Core terms of the agreement".to_string(),
                        field_type: FieldType::TextArea,
                    },
                    ContractPrompt {
                        field: "duration".to_string(),
                        question: "Duration or end date:".to_string(),
                        placeholder: "e.g., 12 months or 2026-12-31".to_string(),
                        required: true,
                        help_text: "How long the agreement lasts".to_string(),
                        field_type: FieldType::Text,
                    },
                    ContractPrompt {
                        field: "jurisdiction".to_string(),
                        question: "Governing law jurisdiction:".to_string(),
                        placeholder: "e.g., New York, USA".to_string(),
                        required: true,
                        help_text: "Which laws apply".to_string(),
                        field_type: FieldType::Text,
                    },
                ],
            },
        ];

        for template in templates {
            self.templates.insert(template.id.clone(), template);
        }
    }

    pub fn get_template(&self, id: &str) -> Option<&ContractTemplate> {
        self.templates.get(id)
    }

    pub fn list_templates(&self) -> Vec<&ContractTemplate> {
        self.templates.values().collect()
    }

    pub fn by_category(&self, category: ContractCategory) -> Vec<&ContractTemplate> {
        self.templates.values()
            .filter(|t| t.category == category)
            .collect()
    }

    /// Generate a contract using the LLM router.
    pub fn generate(&self, template_id: &str, answers: HashMap<String, String>) -> Result<GeneratedContract, String> {
        let template = self.templates.get(template_id)
            .ok_or_else(|| "Template not found".to_string())?;

        // Validate required fields
        for prompt in &template.prompts {
            if prompt.required && !answers.contains_key(&prompt.field) {
                return Err(format!("Required field '{}' not provided", prompt.field));
            }
        }

        // Build user prompt for the LLM
        let user_prompt = self.build_user_prompt(template, &answers);

        // Try LLM generation; fall back to basic response if router not configured
        let llm_response = self.call_llm(&user_prompt)?;

        let disclaimer = self.get_legal_disclaimer();
        let content = format!("{}\n\n{}", llm_response.content, disclaimer);

        Ok(GeneratedContract {
            title: llm_response.title,
            content,
            plain_english_summary: llm_response.plain_english_summary,
            disclaimer,
        })
    }

    /// Build the user prompt sent to the LLM from template metadata and user answers.
    fn build_user_prompt(&self, template: &ContractTemplate, answers: &HashMap<String, String>) -> String {
        use std::fmt::Write;
        let mut prompt = String::new();
        writeln!(&mut prompt, "CONTRACT TYPE: {}", template.name).ok();
        writeln!(&mut prompt, "CATEGORY: {:?}", template.category).ok();
        writeln!(&mut prompt, "DESCRIPTION: {}", template.description).ok();
        writeln!(&mut prompt).ok();
        writeln!(&mut prompt, "--- USER ANSWERS ---").ok();

        for prompt_def in &template.prompts {
            let answer = answers.get(&prompt_def.field)
                .map(|s| if s.is_empty() { "Not provided" } else { s.as_str() })
                .unwrap_or("Not provided");
            writeln!(&mut prompt, "{}: {}", prompt_def.field, answer).ok();
        }

        writeln!(&mut prompt).ok();
        writeln!(&mut prompt, "Generate a complete legal contract based on the above information. Return ONLY valid JSON in the format specified by the system prompt.").ok();

        prompt
    }

    /// Call the LLM router with the generated prompt and parse the response.
    fn call_llm(&self, user_prompt: &str) -> Result<LlmContractResponse, String> {
        let router = self.llm_router.as_ref()
            .ok_or_else(|| {
                "API keys not configured. Please set your API keys in Settings to generate contracts.".to_string()
            })?;

        // We need a runtime to call the async generate() method.
        let runtime = tokio::runtime::Runtime::new()
            .map_err(|e| format!("Failed to create Tokio runtime: {}", e))?;

        let request = GenerationRequest {
            profile: LLMProfile::Structured,
            prompt: user_prompt.to_string(),
            system_prompt: Some(CONTRACT_SYSTEM_PROMPT.to_string()),
            temperature: 0.3,
            max_tokens: 4096,
        };

        let response = runtime
            .block_on(async { router.generate(request).await })
            .map_err(|e| format!("LLM generation failed: {}", e))?;

        let content = response.content.trim().to_string();

        // Try to parse the JSON response. The LLM may wrap in ```json...``` fences.
        let cleaned = if content.starts_with("```") {
            let mut lines = content.lines().collect::<Vec<_>>();
            if lines.first().map(|l| l.starts_with("```")).unwrap_or(false) {
                lines.remove(0);
            }
            if lines.last().map(|l| l.starts_with("```")).unwrap_or(false) {
                lines.pop();
            }
            lines.join("\n").trim().to_string()
        } else {
            content.clone()
        };

        let parsed: LlmContractResponse = serde_json::from_str(&cleaned)
            .map_err(|e| format!("Failed to parse LLM response as JSON: {}\nRaw: {}", e, content))?;

        Ok(parsed)
    }

    fn get_legal_disclaimer(&self) -> String {
        r#"
================================================================================
IMPORTANT LEGAL DISCLAIMER
================================================================================

This contract template is provided for informational purposes only
and does not constitute legal advice. The generator is not a lawyer
or law firm and is not a substitute for professional legal counsel.

BEFORE SIGNING THIS AGREEMENT:

1. HAVE A LAWYER REVIEW: Consult with a qualified attorney licensed
   in your jurisdiction to ensure this contract meets your specific
   needs and complies with local laws.

2. CUSTOMIZE FOR YOUR SITUATION: This is a template that may need
   modifications to fit your unique circumstances.

3. UNDERSTAND THE TERMS: Do not sign any contract you do not fully
   understand. Ask questions and seek clarification.

4. CONSIDER LOCAL LAWS: Contract laws vary by state, country, and
   jurisdiction. What works in one place may not work in another.

5. COMPLEX TRANSACTIONS: For high-value, complex, or high-risk
   agreements, always work with a qualified attorney.

By using this contract, you acknowledge that you understand this is a
template only and assume all responsibility for its use. The creators
of this tool disclaim all liability for any disputes, losses, or
damages arising from the use of this template.

Last Updated: 2026
"#.to_string()
    }
}
